document.write(3*3);
document.write(4/2);
var a=5+10;
document.write(a);
var b=55-28;
document.write(b);
var c=10*2;
document.write(c);
var d="3+6";
document.write(d);
var e="2+3";
var f="4-1";
document.write(e);
document.write("<br>");
document.write(f);
var g=5*5;
var h="5*5";
document.write(h+"="+g);
var abc1=10%3;
document.write(abc1);
var abc2=5%2;
document.write("５÷２の余りは"+abc2);
var abc3="8%2";
document.write(abc3);
var abc4=3%2;
var abc5=1;
document.write(abc4+"="+abc5);
