var a1=3;
document.write(++a1);
var a2=20;
document.write(++a2);
var a2=20;
document.write(++a2);
var a3=10;

document.write(++a3);
document.write("<br>");
document.write(++a3);
var a4=5;
document.write(a4++);
document.write("<br>");
document.write(a4++);
document.write("<br>");
document.write(a4++);
var a5=15;
document.write(--a5);
document.write("<br>");
document.write(--a5);
var a6=20;
document.write(a6--);
document.write("<br>");
document.write(a6--);
document.write("<br>");
document.write(a6--);
var a7=2;
document.write(a7--);
document.write(a7--);
document.write(a7--);
var a8=2;
document.write(++a8);
document.write(a8++);
document.write("<br>");
document.write(a8);
var a9=1;
document.write(a9++);
document.write("<br>");
document.write(a9++);
document.write(<br>);
document.write(a9);